# -*- coding: utf-8 -*-
"""Image_processing_Asst1_SRajeshKanna.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GTzdmHSNfxlzf-oOXFTkiCR-ea-zcNoN
"""

import imageio.v3 as iio
import matplotlib.pyplot as plt
import numpy as np

image_path = r'image/eight_image.tif'

eight = iio.imread(image_path)
print(type(eight))
plt.imshow(eight)
plt.axis('off')  # Optional: turn off axis labels
plt.show()

zero = iio.imread(r'image/eight_image.tif')
zero [1,1] = 1.0
zero [2,1] = 1.0
zero [3,1] = 1.0
plt.imshow(zero)

one = iio.imread(r'image/eight_image.tif')
one [0,0] = 1.0
one [1,0] = 1.0
one [1,1] = 0.0
one [2,0] = 1.0
one [3,0] = 1.0
one [4,0] = 1.0
one [0,2] = 1.0
one [1,2] = 1.0
one [2,2] = 1.0
one [3,2] = 1.0
one [3,1] = 0.0
one [4,2] = 1.0
plt.imshow(one)

two = iio.imread(r'image/eight_image.tif')
two [1,0] = 1.0
two [1,1] = 1.0
two [3,1] = 1.0
two [3,2] = 1.0
plt.imshow(two)

three = iio.imread(r'image/eight_image.tif')
three [1,0] = 1.0
three [1,1] = 1.0
three [3,0] = 1.0
three [3,1] = 1.0
plt.imshow(three)

four = iio.imread(r'image/eight_image.tif')
four [0,1] = 1.0
four [1,1] = 1.0
four [3,0] = 1.0
four [3,1] = 1.0
four [4,0] = 1.0
four [4,1] = 1.0
plt.imshow(four)

five = iio.imread(r'image/eight_image.tif')
five [1,1] = 1.0
five [1,2] = 1.0
five [3,0] = 1.0
five [3,1] = 1.0
plt.imshow(five)

six = iio.imread(r'image/eight_image.tif')
six [1,1] = 1.0
six [1,2] = 1.0
six [3,1] = 1.0
plt.imshow(six)

seven = iio.imread(r'image/eight_image.tif')
seven [1,0] = 1.0
seven [2,0] = 1.0
seven [3,0] = 1.0
seven [4,0] = 1.0
seven [1,1] = 1.0
seven [2,1] = 1.0
seven [3,1] = 1.0
seven [4,1] = 1.0
plt.imshow(seven)

eight = iio.imread(r'image/eight_image.tif')

eight[1, 1] = 1.0
eight[3, 1] = 1.0

plt.imshow(eight)

nine = iio.imread(r'image/eight_image.tif')
nine [1,1] = 1.0
nine [3,0] = 1.0
nine [3,1] = 1.0
plt.imshow(nine)